# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dinov2',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/dinov2',
                'lib_path': 'dinov2'},
  'syms': {'dinov2.core': {'dinov2.core.foo': ('core.html#foo', 'dinov2/core.py')}}}
